version: '3.8'

services:
  kubo:
    image: ipfs/kubo:latest
    container_name: kubo
    networks:
      - app_network
    ports:
      - "5001:5001"   # API
      - "8080:8080"   # Gateway
      - "4001:4001"   # Swarm
    environment:
      - IPFS_PROFILE=server
    command: daemon --migrate=true --agent-version-suffix=docker

  orbitdb:
    build:
      context: ./orbitdb-service
    container_name: orbitdb
    networks:
      - app_network
    #ports:
    #  - "3000:3000"
    environment:
      - NODE_ENV=production
    depends_on:
      - kubo

  go-server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: go-server
    networks:
      - app_network
    #ports:
    #  - "80:80"
    environment:
      - IPFS_API_URL=http://kubo:5001
      - ORBITDB_API_URL=http://orbitdb:3000
    depends_on:
      - kubo
      - orbitdb

networks:
  app_network:
    name: app_network
    driver: bridge